# 1. Import Libraries

In [32]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import string
import csv
from wordcloud import WordCloud

from sklearn.feature_extraction.text import CountVectorizer

## 2. Import Preprocessed data

### 2.1 Positive

In [33]:
with open("../bow-data/positive.csv", newline="") as f:
    reader = csv.DictReader(f)
    data = list(reader)

positive_df = pd.DataFrame(data)

# convert dates to datetime
positive_df['at'] = pd.to_datetime(positive_df['at'])

positive_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,fde4f8c6-06c5-4d58-b5d8-2f12540509b6,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,steam app great way interact friends access st...,5,6,3.10.9,2026-03-11 00:07:34,,,3.10.9
1,8448fd1d-9f20-4762-9711-dd77a0d750d2,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,like interface lot think easy use main reason ...,5,223,3.10.5,2025-08-16 16:09:10,,,3.10.5
2,61cf9985-2aba-407a-95da-c046e37ad094,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,steam best refund game buy like constant disco...,5,0,3.10.7,2026-03-17 23:04:08,,,3.10.7
3,26f389ce-a7fd-4ecd-983c-c873414a13e5,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,steam honestly one greatest apps ever make cou...,5,33,3.10.7,2026-02-25 00:37:11,,,3.10.7
4,f43d8462-bf9c-4594-88de-3bc03905da19,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,tf2 tf2 tf2 tf2 get wrong absolutely terrible ...,5,2,3.10.9,2026-03-13 09:43:53,,,3.10.9

### 2.2 Negative

In [34]:
with open("../bow-data/negative.csv", newline="") as f:
    reader = csv.DictReader(f)
    data = list(reader)

negative_df = pd.DataFrame(data)

# convert dates to datetime
negative_df['at'] = pd.to_datetime(negative_df['at'])

negative_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,c2e5379e-089d-49a7-9b12-a2911d8177d9,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,absolutely useless steam pc problems able use ...,1,5,3.10.9,2026-03-10 12:03:24,,,3.10.9
1,008891c9-1f0f-43ec-a7b3-2e0c1816b93d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,try well hour log app change password account ...,1,220,3.10.6,2026-01-20 07:50:24,,,3.10.6
2,11a6bbe2-abad-48c2-a60a-eef4868fbdf0,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,download today login password way long even th...,1,22,,2026-01-21 07:39:28,,,
3,0283b618-aa4d-4b82-abb3-5c48c3084f8d,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,work good steam browse shop however yesterday ...,1,626,3.6.5,2023-08-23 23:23:10,,,3.6.5
4,1b9897f8-c4f0-49e7-b624-a4639c6d78a9,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,never write review wow actually impress unusab...,1,581,3.7.2,2023-12-09 07:56:51,,,3.7.2

## 3. BoW Analysis

In [ ]:

def generate_bow(content):
    out = {}
    text_tokens = content.split(" ")

    for token in text_tokens:
        if token in out:
            out[token] += 1
        else:
            out[token] = 1
    
    return out

print("Positive bags of words:")
for content in positive_df["content"]:
    positive_bow = generate_bow(content)
    print(positive_bow)

Positive bag of words:
{'steam': 3, 'app': 1, 'great': 2, 'way': 2, 'interact': 1, 'friends': 2, 'access': 2, 'account': 2, 'mobile': 1, 'instead': 1, 'use': 1, 'web': 1, 'browser': 1, 'desktop': 2, 'version': 2, 'little': 1, 'slower': 1, 'slightly': 1, 'clunky': 1, 'however': 1, 'update': 1, 'information': 1, 'chat': 2, 'two': 1, 'authentication': 2, 'enable': 1, 'might': 1, 'get': 1, 'loop': 1, 'disable': 1, 'delete': 1, 'reinstall': 1, 'work': 1}
{'like': 1, 'interface': 1, 'lot': 1, 'think': 1, 'easy': 1, 'use': 2, 'main': 1, 'reason': 1, 'give': 1, '5': 1, 'star': 1, 'support': 3, 'lose': 1, 'access': 2, 'authenticator': 1, 'account': 1, 'due': 1, 'years': 1, 'want': 1, 'back': 1, 'realize': 1, 'lock': 1, 'team': 2, 'work': 1, 'hard': 1, 'help': 1, 'regain': 1, 'stupidity': 1, 'get': 1, 'keep': 1, 'one': 1, 'game': 1, 'actually': 1, 'buy': 1, 'point': 1, 'username': 1, 'pretty': 1, 'attach': 1, 'say': 1, 'steam': 1, 'awesome': 1}
{'steam': 1, 'best': 1, 'refund': 1, 'game': 3, 'buy': 3, 'like': 1, 'constant': 1, 'discount': 1, 'allow': 1, 'us': 2, 'even': 1, 'normally': 1, 'budget': 1, 'easy': 1, 'love': 1, 'company': 2, 'one': 1, 'leave': 1, 'actually': 1, 'care': 1, 'customers': 1, 'see': 1, 'cash': 1, 'cow': 1}
{'steam': 3, 'honestly': 2, 'one': 1, 'greatest': 1, 'apps': 2, 'ever': 2, 'make': 1, 'countless': 1, 'game': 2, 'endless': 1, 'opportunities': 1, 'customer': 2, 'service': 1, 'chart': 1, 'amaze': 1, 'think': 1, 'best': 1, 'support': 1, 'experience': 1, 'life': 1, 'lightweight': 1, 'easy': 1, 'manage': 1, 'app': 1, 'superior': 1, 'thank': 1}
{'tf2': 6, 'get': 1, 'wrong': 1, 'absolutely': 1, 'terrible': 2, 'laptop': 1, 'aim': 1, 'genuinely': 1, 'love': 1, 'game': 3, 'character': 1, 'point': 1, 'lowky': 1, 'gooned': 1, 'twice': 1, 'really': 2, 'proud': 1, 'good': 3, 'way': 1, 'describe': 1, 'without': 1, 'tell': 1, 'whole': 1, 'lore': 1, 'alongside': 1, 'weapon': 1, 'stats': 1, 'yeah': 1, 'steam': 1, 'company': 1, 'ngl': 1, 'best': 1}
{'know': 1, 'game': 2, 'pay': 2, 'play': 1, 'neccessarily': 1, 'help': 1, 'take': 1, 'money': 1, 'buy': 1, 'steam': 1, 'sucker': 1, 'platformers': 1, 'get': 1, 'toree': 1, '2': 1, 'free': 1, 'app': 1, 'lot': 1, 'optimize': 1, 'actual': 1, 'console': 1}
{'sure': 1, 'many': 1, 'people': 1, 'issue': 2, 'app': 1, 'use': 1, 'since': 1, '2017': 1, 'android': 1, 'devices': 1, 'ios': 1, 'ipados': 1, 'useful': 1, 'case': 1, 'catch': 1, 'deal': 1, 'start': 1, 'remote': 1, 'download': 1, 'new': 1, 'game': 1, 'even': 1, 'patch': 1}
{'love': 1, 'computer': 1, 'game': 1, 'story': 1, 'tell': 1, 'better': 1, 'movie': 1, 'although': 1, 'require': 1, 'think': 1, 'action': 1, 'time': 1, 'hard': 1, 'sip': 1, 'beer': 1, 'play': 1, 'multi': 1, 'task': 1, 'something': 1, 'need': 1, 'make': 1, 'aware': 1, 'download': 1, 'utilize': 1, 'feature': 1, 'app': 1}
{'log': 2, 'steam': 3, 'get': 2, 'new': 2, 'phone': 4, 'number': 3, 'update': 2, 'account': 3, 'also': 1, 'lose': 1, 'recovery': 1, 'cod': 1, 'access': 2, 'authenticator': 2, 'support': 1, 'quick': 1, 'respond': 1, 'super': 1, 'helpful': 1, 'back': 2, 'remove': 1, 'old': 1, 'enable': 1, 'w': 1, 'happy': 1, 'relieve': 1, 'game': 1, 'purchase': 1, 'thank': 1}
{'use': 1, '3': 1, 'years': 1, 'improve': 1, 'quite': 1, 'lot': 1, 'important': 1, 'part': 1, 'access': 1, 'steam': 1, 'wallet': 2, 'miss': 1, 'buy': 1, 'game': 1, 'discount': 1, 'almost': 1, 'go': 1, 'less': 1, '5': 1, 'minute': 1, 'top': 1, 'local': 1, 'e': 1}
{'reason': 1, 'overall': 1, 'rat': 1, 'low': 1, 'people': 1, 'usually': 1, 'bother': 1, 'make': 1, 'something': 1, 'wrong': 1, 'happen': 1, 'run': 1, 'perfectly': 1, 'experience': 1, 'app': 1, 'pretty': 1, 'good': 1, 'though': 1, 'since': 1, 'everything': 1, 'want': 1, 'improve': 1, 'lot': 1, 'time': 1}
{'steam': 2, 'appreciation': 1, 'review': 1, 'much': 1, 'better': 1, 'every': 1, 'online': 1, 'game': 1, 'store': 2, 'want': 1, 'use': 1, 'name': 1, 'limit': 1, 'payment': 1, 'options': 1, 'compatible': 1, 'literally': 1, 'anything': 1, 'everything': 1, 'even': 1, 'get': 2, 'start': 1, 'good': 1, 'customer': 1, 'service': 1, 'always': 1, 'solve': 1, 'problems': 1, 'within': 1, 'day': 1, 'one': 1, 'thing': 1, 'improve': 1, 'sell': 1, 'inventory': 1, 'item': 1, 'wait': 1, 'time': 1, 'money': 1, 'long': 1}
{'literally': 1, 'absolute': 1, 'best': 2, 'customer': 1, 'service': 1, 'world': 1, 'account': 2, 'glitching': 2, 'buy': 1, 'game': 4, 'try': 1, 'time': 1, 'respond': 1, 'within': 2, '30': 1, 'minutes': 1, 'whole': 1, 'issue': 1, 'resolve': 1, '1': 1, '5': 1, 'hours': 1, 'refund': 2, 'put': 1, 'wrong': 1, 'address': 1, 'take': 1, 'money': 1, 'steam': 1, 'say': 1, 'decline': 1, 'bank': 1, 'later': 1, 'automatically': 1, 'get': 1, 'basically': 1, 'one': 1, 'safety': 1, 'net': 1, 'servic': 1}
{'best': 2, 'support': 2, 'squad': 1, 'helpful': 1, 'long': 1, 'provide': 1, 'information': 1, 'course': 1, 'lost': 1, 'account': 1, 'get': 1, 'back': 1, 'thank': 1, 'steam': 1, 'better': 1, 'discord': 1}
{'thank': 1, 'login': 1, 'without': 1, 'issue': 1, 'happen': 1, 'yesterday': 1, 'let': 1, 'log': 1, 'in': 1, 'least': 1, 'work': 1}
{'best': 1, 'way': 1, 'buy': 1, 'pc': 1, 'game': 1, 'support': 1, 'team': 1, 'good': 1, 'nice': 1, 'always': 1, 'help': 1, 'recover': 1, 'account': 1, 'thank': 1}
{'program': 1, 'great': 1, 'years': 1, 'experience': 1, 'steam': 1, 'available': 1, 'smartphones': 1, 'still': 1, 'game': 1, 'perspective': 1}
{'explain': 1, 'happen': 1, 'accaunt': 1, 'even': 1, 'hessitate': 1, 'take': 1, 'action': 1, 'help': 2, 'expect': 1, 'see': 1, 'fast': 1, 'tick': 1, 'course': 1, 'best': 1, 'platform': 1, 'word': 1, 'thenk': 1, 'enaugh': 1}
{'deal': 1, 'amaze': 1, 'fist': 1, 'game': 1, 'company': 1, 'corrupt': 1, '£150': 1, 'others': 1, '£17': 1, 'steam': 1, 'save': 1, 'much': 1, 'money': 1}
{'10': 4, 'app': 2, 'even': 1, 'let': 1, 'download': 1, 'mods': 1, 'game': 2, 'without': 1, 'turn': 1, 'laptop': 1, 'plus': 1, 'simple': 1, 'cheap': 1, 'thank': 1, 'gabe': 1, 'make': 1, 'find': 1, 'problem': 1, 'far': 1}
{'nice': 1, 'guy': 1, 'update': 1, 'ui': 1, 'overall': 1, 'user': 1, 'experience': 1, 'app': 1, 'feel': 1, 'outdated': 1, 'yes': 1, 'work': 1, 'better': 1}
{'steam': 3, 'app': 2, 'android': 2, 'really': 1, 'good': 1, 'think': 1, 'need': 1, 'add': 2, 'feature': 1, 'better': 1, 'experience': 1, 'like': 1, 'wishlist': 3, 'counter': 1, 'get': 1, 'back': 1, 'game': 2, 'page': 2, 'scroller': 1, 'go': 2, 'stay': 1, 'exact': 1, 'position': 1, 'leave': 1, 's': 1, 'please': 1, 'consider': 1, 'suggestion': 1}
{'around': 1, 'great': 1, 'experience': 1, 'need': 1, 'like': 1, 'desktop': 1, 'version': 1}
{'trouble': 1, 'pay': 1, 'bundle': 1, 'deal': 1, 'think': 1, 'able': 1, 'purchase': 2, 'since': 1, 'discount': 2, 'turn': 1, 'steam': 1, 'support': 1, 'notice': 1, 'plight': 1, 'allow': 1, 'still': 1, 'honestly': 1, 'best': 1, 'experience': 1, 'app': 1}
{'valve': 1, 'game': 2, 'app': 2, 'honestly': 1, 'gamenative': 1, 'gamehub': 1, 'already': 2, 'good': 1, 'enough': 1, 'experience': 1, 'play': 1, 'steam': 1, 'android': 1}
{'compact': 1, 'useful': 1, 'able': 1, 'view': 1, 'store': 1, 'marketplace': 1, 'app': 1, 'w': 1, 'need': 1, 'open': 1, 'browser': 1, 'much': 1, 'smoother': 1, 'experience': 1}
{'work': 1, 'fine': 1, 'case': 1, 'need': 1, 'check': 1, 'discount': 1, 'shop': 1, 'game': 1, 'importantly': 1, 'login': 1, 'key': 1, 'anywhere': 1, 'yeah': 1, 'sure': 1, 'perfect': 2, 'see': 1, 'later': 1, 'arm': 1, 'base': 1, 'project': 1, 'succeed': 1, 'shift': 1, 'focus': 1, 'make': 1, 'app': 1}
{'thank': 1, 'steam': 1, 'really': 2, 'great': 1, 'service': 2, 'help': 1, 'get': 2, 'account': 2, 'back': 2, 'happy': 1, 'keep': 1, 'good': 1, 'work': 1}
{'work': 1, 'fine': 1, 'encounter': 1, 'issue': 1}
{'app': 3, 'good': 1, 'miss': 1, 'sosme': 1, 'system': 1, 'requierments': 1, 'software': 1, 'check': 1, 'suggest': 1, 'witch': 1, 'work': 1, 'us': 1}
{'try': 2, 'sign': 3, 'like': 1, '40': 1, 'minutes': 1, 'keep': 2, 'say': 1, 'error': 1, 'something': 2, 'first': 1, 'internet': 1, 'roblox': 1, 'play': 2, 'smoothly': 1, 'app': 3, 'let': 1, 'notice': 1, 'get': 1, 'frickin': 1, 'log': 1, 'acc': 1, 'pc': 1, 'anyways': 1, 'fix': 1, 'ui': 1, 'ok': 2, 'good': 1, 'game': 1, 'stuff': 1, '3': 1, 'star': 2, 'time': 1, 'finally': 1, 'change': 1, '5': 1, 'yey': 1}
{'good': 1, 'app': 2, 'make': 1, 'easy': 1, 'boyfriend': 1, 'love': 1, 'play': 1, 'game': 2, 'friends': 1}
{'account': 2, 'get': 2, 'hack': 1, 'solution': 1, 'report': 1, 'steam': 2, 'support': 2, 'ban': 1, 'hacker': 1, 'instantly': 2, 'back': 1, 'also': 1, 'forget': 1, 'password': 1, 'give': 1, '1': 1, 'verification': 1, 'check': 1, 'love': 1, 'people': 1, 'r': 1, 'absolute': 1, 'best': 1}
{'really': 1, 'write': 1, 'review': 1, 'fantastic': 1, 'customer': 1, 'service': 2, 'receive': 1, 'request': 1, 'necessarily': 1, 'app': 3, 'monitor': 1, 'account': 1, 'access': 1, 'however': 1, 'download': 1, 'play': 1, 'game': 1, 'look': 1, 'thank': 1, 'steam': 1, 'team': 1, 'answer': 1, 'question': 1}
{'great': 1, 'companion': 1, 'app': 2, 'desktop': 1, 'version': 1, 'browse': 1, 'steam': 1, 'store': 1, 'buy': 1, 'game': 3, 'remotely': 1, 'play': 1, 'think': 1, 'majority': 1, 'honest': 1, 'even': 1, 'design': 1, 'run': 1, 'android': 1, 'os': 1}
{'love': 1, 'app': 1, 'customer': 1, 'service': 3, 'issue': 1, 'steam': 3, 'deck': 1, 'delivery': 1, 'resolve': 1, 'promptly': 1, 'always': 1, 'pc': 1, 'gamer': 1, 'continue': 2, 'use': 1, 'long': 1, 'stellar': 1, 'products': 1}
{'store': 1, 'tag': 3, 'section': 1, 'little': 1, 'break': 1, 'visually': 1, 'click': 2, 'anything': 1, 'tabs': 1, 'global': 1, 'friends': 1, 'recommend': 1, 'see': 1, 'list': 1, 'well': 1, 'game': 1, 'overlay': 1, 'either': 1}
{'idea': 1, 'complaints': 1, 'yap': 1, 'personally': 1, 'love': 1, 'app': 1, 'high': 1, 'quality': 1, 'update': 1, 'consistently': 1, 'laptop': 1, 'account': 1, 'great': 1, 'feature': 1, 'like': 1, 'qr': 1, 'code': 1, 'sign': 1, 'must': 1, 'steam': 2, 'users': 1, 'frequently': 1, 'play': 1, 'game': 1}
{'use': 1, '5': 1, 'years': 1, 'never': 1, 'issue': 1, 'work': 1, 'great': 1, 'even': 1, 'lose': 1, 'phone': 1, 'get': 1, 'new': 1, 'one': 1, 'easy': 1, 'transfer': 1, 'steam': 1, 'support': 1, 'best': 1, 'far': 1}
{'absolute': 1, 'cinema': 1, 'steam': 3, 'best': 1, 'platform': 1, 'game': 1, 'ever': 1, 'make': 1, 'accout': 1, 'steal': 1, 'password': 1, 'email': 1, 'change': 1, 'reach': 1, 'support': 2, 'problem': 1, 'fix': 1, 'matter': 1, 'hours': 1, 'thank': 1, 'kelly': 1}
{'great': 1, 'app': 1, 'wat': 1, 'till': 1, 'fex': 1, 'proton': 1, 'support': 2, 'finally': 1, 'play': 1, 'windows': 1, 'pc': 1, 'game': 1, 'powerful': 1, 'android': 1, 'phone': 1, 'hope': 1, 'come': 1, 'year': 1}
{'absolutely': 1, 'love': 1, 'steam': 1, 'sales': 1, 'insane': 1, 'valve': 1, 'general': 1, 'one': 1, 'pro': 1, 'consumer': 1, 'entities': 1, 'game': 1, 'world': 1, 'app': 1, 'great': 1, 'easy': 1, 'use': 1}
{'app': 1, 'steam': 3, 'guard': 1, 'save': 1, 'account': 2, 'get': 1, 'hack': 1, 'due': 1, 'impersonate': 1, 'moderators': 1, 'whatnots': 1, 'high': 1, 'security': 1, 'rat': 1, 'five': 1, 'star': 1}
{'mobile': 1, 'version': 1, 'well': 1, 'currently': 1, 'steam': 1, 'still': 1, 'goated': 1, 'anything': 1, 'less': 1, '5': 1, 'star': 1, 'unacceptable': 1}
{'really': 1, 'help': 2, 'best': 1, 'account': 2, 'service': 1, 'reset': 1, 'lose': 1, 'password': 1, 'thank': 1}
{'best': 1, 'customer': 1, 'service': 1, 'ever': 1, 'face': 1, 'issue': 1, 'login': 1, 'account': 1, 'steam': 1, 'support': 1, 'team': 1, 'fix': 1, 'hour': 1}
{'rat': 1, 'low': 1, 'new': 1, 'ui': 1, 'work': 1, 'progress': 1}
{'people': 1, 'much': 1, 'honest': 1, 'heart': 1, 'among': 1, 'experience': 1, 'applications': 1, 'see': 1, 'rat': 1, 'screen': 1}
{'must': 1, 'want': 1, 'get': 1, 'good': 1, 'deal': 1, 'also': 1, 'customisable': 1}
{'best': 3, 'game': 1, 'app': 2, 'ever': 1, 'get': 1, 'problem': 2, 'help': 2, 'rust': 3, 'playtime': 1, '3': 1, 'hours': 1, 'make': 1, 'exception': 1, 'give': 1, 'money': 1, 'steam': 1, 'cost': 1, 'remove': 1}

In [47]:
print("Negative bags of words:")
for content in negative_df["content"]:
    negative_bow = generate_bow(content)
    print(negative_bow)

Negative bags of words:
{'absolutely': 1, 'useless': 1, 'steam': 2, 'pc': 1, 'problems': 1, 'able': 1, 'use': 1, 'app': 2, 'longtime': 1, 'afraid': 1, 'uninstall': 1, 'phone': 1, 'might': 1, 'effectively': 1, 'keep': 1, 'log': 2, 'desktop': 1, 'guard': 1, 'much': 1, 'money': 1, 'tie': 1, 'game': 1, 'library': 1, 'get': 1, 'screw': 1, 'absolute': 1, 'pain': 1}
{'try': 1, 'well': 1, 'hour': 1, 'log': 2, 'app': 1, 'change': 1, 'password': 1, 'account': 1, 'continuously': 1, 'get': 1, 'error': 1, 'server': 1, 'issue': 1, 'thus': 1, 'frustrate': 1, 'confuse': 1, 'love': 1, 'use': 1, 'steam': 1, 'phone': 1, 'share': 1, 'game': 1, 'play': 1, 'friends': 1, 'go': 1, 'unable': 1, 'feel': 1, 'bug': 1, 'rather': 1, 'end': 1, 'hope': 1, 'fix': 1}
{'download': 2, 'today': 1, 'login': 2, 'password': 2, 'way': 1, 'long': 1, 'even': 2, 'though': 1, 'know': 1, 'correct': 1, 'update': 1, 'still': 2, 'work': 1, 'double': 1, 'check': 1, 'username': 1, 'yep': 1, 'right': 1, 'go': 1, 'whole': 1, 'process': 1, 'third': 1, 'time': 2, 'copy': 1, 'paste': 1, 'note': 1, 'app': 2, 'make': 1, 'sure': 1, 'input': 1, 'correctly': 1, 'nada': 1, 'infuriate': 1, 'try': 1, 'couple': 1, 'years': 1, 'never': 1}
{'work': 2, 'good': 1, 'steam': 2, 'browse': 1, 'shop': 1, 'however': 1, 'yesterday': 1, 'app': 2, 'stop': 1, 'entirely': 1, 'first': 1, 'log': 3, 'in': 2, 'reopen': 1, 'blank': 1, 'screen': 1, 'issue': 1, 'see': 1, 'others': 1, 'report': 1, 'well': 1, 'download': 1, 'never': 1, 'try': 1, 'change': 1, 'password': 1, 'result': 1, 'lose': 1, 'access': 1, 'account': 1, 'able': 1, 'confirm': 1, 'trade': 1, 'offer': 1, 'etc': 1, 'unless': 1, 'reinstall': 1, 'whole': 1, 'move': 1, 'authenticator': 1, 'time': 1}
{'never': 1, 'write': 1, 'review': 1, 'wow': 1, 'actually': 1, 'impress': 1, 'unusable': 1, 'app': 1, 'get': 1, 'stick': 1, 'steam': 1, 'guard': 1, 'try': 2, 'inputting': 1, 'code': 1, 'send': 1, 'email': 1, 'randomly': 1, 'put': 1, 'box': 1, 'delete': 1, 'helplessly': 1, 'input': 1, 'correct': 1, 'order': 1, 'finally': 1, 'happen': 1, 'errors': 1, 'start': 1, 'previous': 1, 'screen': 1, 'anyways': 1}
{'believe': 1, 'possible': 1, 'actually': 1, 'make': 1, 'app': 2, 'worse': 1, 'latest': 1, 'update': 1, 'use': 1, 'store': 1, 'much': 1, 'slower': 1, 'laggy': 1, 'compare': 1, 'previous': 1, 'version': 1, 'suddenly': 1, 'bunch': 1, 'notifications': 1, 'bombard': 1, 'game': 2, 'sales': 1, 'even': 2, 'wishlist': 1, 'need': 1, 'notification': 1, 'every': 1, 'sale': 1, 'worst': 1, 'though': 1, 'removable': 1, 'friends': 1, 'list': 1, 'care': 1, 'chat': 1, 'anymore': 1, 'able': 1, 'see': 1, 'online': 1, 'awful': 1}
{'gutted': 1, 'ruin': 1, 'app': 3, 'make': 2, 'download': 1, '2': 1, 'separate': 1, 'apps': 1, 'try': 1, 'get': 1, 'functionality': 1, 'one': 2, 'use': 1, 'fine': 1, 'except': 1, 'neither': 1, 'things': 1, 'well': 1, 'old': 1, 'edit': 1, 'additionally': 1, 'purchase': 1, 'already': 1, 'log': 3, 'ask': 2, 'jump': 1, '2fa': 1, 'hoop': 1, 'endless': 1, 'loop': 1, 'also': 1, 'let': 1, 'contact': 1, 'support': 1}
{'old': 1, 'app': 2, 'fine': 2, 'work': 1, 'exactly': 1, 'like': 1, 'pc': 1, 'store': 1, 'version': 2, 'slow': 1, 'asf': 1, 'full': 1, 'webpages': 1, 'even': 1, 'display': 1, 'example': 1, 'ill': 1, 'go': 1, 'workshop': 1, 'page': 2, 'mod': 1, 'game': 1, 'text': 1, 'perfectly': 1, 'image': 1, 'half': 1, 'unseeable': 1, 'scroll': 1, 'leave': 1, 'right': 1, 'frustrate': 1, 'whenever': 1, 'try': 1, 'use': 2, 'website': 1, 'instead': 1, 'autodirects': 1, 'back': 1, 'want': 1, 'desktop': 1, 'let': 1}
{'work': 1, 'great': 1, 'even': 1, 'buggier': 1, 'old': 1, 'steam': 3, 'app': 1, 'nearly': 1, 'every': 2, 'time': 1, 'open': 1, 'manually': 1, 'kill': 2, 'restart': 1, 'bad': 2, 'state': 1, 'spend': 1, 'effort': 1, 'style': 1, 'cut': 1, 'qa': 1, 'corner': 1, 'possibly': 1, 'use': 1, 'tasker': 1, 'create': 1, 'shortcut': 1, 'relaunch': 1, 'one': 1, 'press': 1, 'edit': 1, '2': 1, 'years': 1, 'later': 1, 'still': 1, 'true': 1}
{'joke': 1, 'right': 1, 'everything': 1, 'app': 2, 'worse': 1, 'try': 2, 'give': 1, 'chance': 1, 'even': 1, 'maneuver': 1, 'interface': 1, 'without': 1, 'immense': 1, 'amount': 1, 'redundancy': 1, 'take': 1, '4': 1, '6': 1, 'press': 1, 'get': 2, 'store': 1, 'homepage': 1, 'see': 1, 'page': 2, 'several': 1, 'time': 1, 'horrible': 1, 'experience': 1, 'constantly': 1, 'redirect': 1, 'discussion': 1, 'lose': 1, 'text': 1, 'cart': 1, 'desktop': 1, 'sync': 1, 'reason': 1, 'community': 1, 'market': 1, 'awful': 1}
{'app': 2, 'complete': 1, 'waste': 1, 'time': 1, 'never': 1, 'download': 1, 'steam': 1, 'make': 1, 'mandatory': 1, 'sell': 2, 'inventory': 1, 'items': 1, 'marketplace': 1, 'set': 1, 'take': 1, 'three': 1, 'days': 1, 'do': 1, 'bug': 1, 'input': 1, 'sms': 1, 'cod': 1, 'verification': 1, 'however': 1, 'everytime': 1, 'enter': 1, 'code': 2, 'give': 1, '2': 1, 'error': 1, 'end': 1, 'get': 1, 'account': 1, 'lock': 1, 'two': 1, 'weeks': 1, 'garbage': 2}
{'app': 1, 'bricked': 1, 'account': 2, '1000s': 1, 'dollars': 1, 'game': 3, 'go': 1, 'steam': 2, 'care': 1, 'prove': 1, '2fa': 1, 'policy': 1, 'force': 1, 'throats': 1, 'refuse': 1, 'give': 1, 'shin': 1, 'example': 1, 'never': 1, 'buy': 1, 'anything': 1, 'need': 1, 'bring': 1, 'back': 1, 'physical': 1, 'cart': 1, 'else': 1, 'matter': 1, 'time': 1, 'lose': 1, 'everything': 1, 'hold': 1}
{'hey': 1, 'download': 1, 'steam': 1, 'run': 1, 'issue': 1, 'try': 1, 'create': 2, 'account': 1, 'keep': 1, 'get': 1, 'stick': 1, 'loop': 1, 'email': 2, 'verification': 1, 'despite': 1, 'verify': 1, 'several': 1, 'time': 1, 'recognize': 1, 'already': 1, 'use': 1, 'twice': 1, 'prevent': 1, 'username': 1, 'password': 1, 'maybe': 1, 'something': 1, 'wrong': 1, 'whatever': 1, 'work': 1}
{'terrible': 1, 'update': 1, 'refuse': 1, 'two': 1, 'apps': 1, 'one': 3, 'platform': 1, 'search': 1, 'game': 1, 'chat': 1, 'either': 1, 'app': 2, 'actually': 1, 'work': 1, 'properly': 1, 'really': 1, 'disappoint': 1, 'remove': 1, 'steam': 1, 'mobile': 1, 'altogether': 1, 'things': 1, 'wait': 1, 'get': 1, 'home': 1, 'pc': 1, 'ruin': 1, 'familiar': 1, 'easy': 1, 'use': 1, 'fully': 1, 'functional': 1, 'all': 1, 'in': 1, 'love': 1}
{'say': 2, 'claim': 1, 'fix': 2, 'login': 1, 'issue': 2, 'lie': 1, 'experience': 1, 'mobile': 2, 'pc': 2, 'apps': 1, 'app': 1, 'infinite': 1, 'repeat': 1, 'email': 1, 'verify': 1, 'yet': 1, 'work': 2, 'account': 3, 'creation': 2, 'reset': 1, 'captcha': 1, 'glitches': 1, 'years': 1, 'hate': 1, 'bug': 1, 'seem': 1, 'pile': 1, 'ontop': 1, 'one': 1, 'able': 1, 'make': 1, 'whatever': 1, 'way': 1, 'possible': 1, 'please': 1}
{'update': 1, 'review': 1, '2': 1, 'star': 2, '1': 1, 'app': 2, 'truly': 1, 'awful': 1, 'well': 1, 'general': 1, 'buggy': 1, 'mess': 1, 'browse': 1, 'fail': 3, 'order': 1, 'steam': 2, 'deck': 1, 'cause': 1, 'stick': 1, 'pending': 1, 'transaction': 1, '£349': 1, 'call': 1, 'bank': 1, 'clear': 1, 'also': 1, 'try': 1, 'buy': 1, 'game': 1, 'forget': 1, 'previous': 1, 'ordeal': 1, 'thing': 1, 'happen': 1, 'tell': 1, '3d': 1, 'authentication': 1, 'process': 1, 'true': 1, 'pocket': 1, 'options': 1, 'wait': 1, 'hope': 1}
{'try': 3, 'purchase': 1, 'game': 2, 'app': 4, 'use': 2, 'paypal': 1, 'constantly': 1, 'fail': 2, 'even': 1, 'login': 1, 'open': 3, 'external': 2, 'browser': 3, 'window': 1, 'instead': 1, 'everything': 1, 'in': 1, 'terrible': 1, 'time': 1, 'attempt': 1, 'intercept': 1, 'link': 1, 'steam': 1, 'often': 1, 'get': 1, 'stick': 1, 'one': 1, 'others': 1, 'without': 1, 'completely': 1, 'close': 1, 'things': 1, 'actually': 1, 'work': 1, 'thank': 1}
{'open': 1, 'matter': 1, 'long': 1, 'let': 1, 'try': 1, 'moment': 1, 'click': 1, 'icon': 1, 'get': 1, 'stick': 1, 'grey': 1, 'load': 2, 'screen': 1, 'text': 1, 'parental': 2, 'settings': 2, 'tiny': 1, 'black': 1, 'letter': 1, 'enable': 1, 'able': 1, 'use': 1, 'app': 2, 'small': 1, 'handful': 1, 'time': 1, 'issue': 1, 'begin': 1, 'remember': 1, 'cumbersome': 1, 'frustrate': 1, 'expierence': 1, 'trade': 1, 'force': 1, 'delay': 1, 'acessed': 1, 'week': 1, 'despite': 1, 'fact': 1, 'access': 1}
{'app': 2, 'break': 1, 'clear': 1, 'steam': 2, 'want': 1, 'sell': 1, 'deck': 1, 'fine': 1, 'seem': 1, 'abandon': 1, 'process': 1, 'chore': 1, 'find': 1, 'way': 1, 'go': 1, 'back': 1, 'previously': 1, 'view': 1, 'say': 1, 'paypal': 1, 'use': 1, 'purchase': 1, 'years': 1, 'longer': 1, 'valid': 1, 'even': 1, 'reset': 1, 'problem': 1}
{'use': 3, 'work': 2, 'well': 1, 'get': 1, 'authenticator': 1, 'code': 4, 'either': 1, 'notification': 1, 'widget': 1, 'force': 1, 'open': 1, 'app': 2, 'qr': 1, 'happen': 1, 'select': 1, 'option': 2, 'old': 1, 'system': 1, 'wait': 1, 'instead': 1, 'try': 1, 'make': 1, 'approve': 1, 'deny': 1, 'request': 1, 'base': 1, 'upon': 1, 'ip': 1, 'location': 1, 'tldr': 1, 'log': 2, 'desktop': 1, 'nightmare': 1}
{'take': 1, '20': 1, 'mins': 1, 'send': 1, 'simple': 1, 'message': 2, 'friend': 1, 'new': 1, 'lay': 1, 'friends': 1, 'list': 1, 'bury': 1, 'finally': 1, 'get': 2, 'load': 1, 'completely': 1, 'different': 1, 'tab': 1, 'squish': 1, 'type': 1, 'click': 1, 'fix': 1, 'something': 1, 'break': 1, 'excite': 1, 'switch': 1, 'xbox': 1, 'much': 1, 'hassle': 1}
{'slowest': 1, 'app': 4, 'google': 1, 'play': 1, 'even': 2, 'minor': 1, 'interruption': 1, 'connection': 1, 'become': 1, 'completely': 1, 'unusable': 1, 'browser': 2, 'steam': 3, 'website': 2, 'worse': 1, 'regular': 1, 'every': 1, 'way': 1, 'let': 1, 'chat': 1, 'separate': 1, 'easier': 1, 'faster': 1, 'convenient': 1, 'use': 1, 'require': 1, 'install': 1, '2fa': 1, 'marketplace': 1, 'stuff': 1, 'worst': 1, 'part': 1, 'hand': 1, 'absolutely': 1, 'miserable': 1}
{'want': 1, 'access': 2, 'menu': 2, 'verify': 1, 'code': 2, 'change': 1, 'password': 2, 'without': 1, 'log': 1, 'remember': 1, 'enter': 1, 'see': 1, 'app': 2, 'like': 1, 'make': 1, 'test': 1, 'beyond': 1, 'critical': 1, 'functionality': 1, 'literally': 1, 'useless': 1, 'currently': 1}
{'really': 1, 'want': 2, 'play': 1, 'game': 2, 'see': 1, 'steam': 1, 'however': 1, 'try': 1, 'create': 3, 'account': 3, 'last': 1, 'hour': 1, 'pc': 1, 'phone': 1, 'nothing': 1, 'work': 1, 'captcha': 1, 'keep': 1, 'say': 1, 'responses': 1, 'invalid': 1, 'absolutely': 1, 'ridiculous': 1, 'someone': 1, 'pay': 1, 'site': 1, 'servers': 1, 'software': 1, 'allow': 1}
{'access': 1, 'wishlist': 2, 'add': 1, 'anything': 3, 'say': 3, 'sign': 2, 'uninstalled': 1, 'app': 2, 'reinstall': 1, 'back': 2, 'still': 1, 'let': 1, 'try': 2, 'load': 1, 'profile': 1, 'work': 1, 'server': 1, 'error': 1, 'reload': 1, 'thing': 1, 'know': 1, 'happen': 1, 'fine': 1, 'sudden': 1, 'allow': 1, 'account': 1, 'enjoy': 1, 'roll': 1, 'update': 1, 'unusable': 1}
{'try': 1, 'communicate': 1, 'anyone': 2, 'support': 1, 'byzantine': 1, 'migraine': 1, 'dive': 1, 'app': 3, 'update': 1, 'gain': 1, 'ton': 1, 'functionality': 1, 'lose': 1, 'honestly': 1, 'think': 1, 'rely': 1, 'steam': 2, 'deck': 2, 'manage': 1, 'library': 1, 'kind': 1, 'make': 1, 'impossible': 1, 'really': 1, 'anything': 2, 'spend': 1, 'money': 1, 'leave': 1, 'feedback': 1, 'talk': 1, 'accomplish': 1, 'need': 1, 'phone': 1, 'bluetooth': 1, 'keyboard': 1, 'mouse': 1}
{'instal': 1, 'new': 1, 'update': 1, 'instantly': 1, 'regret': 1, 'reason': 1, 'still': 1, 'try': 1, 'bend': 1, 'app': 1, 'spar': 1, 'seemingly': 1, 'daily': 1, 'verification': 1, 'login': 1, 'dance': 1, 'get': 1, 'chrome': 1, 'mobile': 1, 'half': 1, 'time': 1, 'link': 1, 'steam': 1, 'e': 1, 'g': 1, 'game': 2, 's': 1, 'store': 2, 'page': 2, 'resolve': 1, 'correctly': 1, 'take': 1, 'default': 1, 'main': 1, 'usually': 1, 'something': 1, 'simple': 1, 'see': 1, 'recent': 1, 'activity': 1, 'menu': 1, 'items': 1, 'account': 1, 'overview': 1, 'view': 1, 'also': 1, 'work': 1}
{'strip': 1, 'functionality': 1, 'seemingly': 1, 'reason': 1, 'previously': 1, 'pretty': 1, 'much': 3, 'anything': 1, 'want': 1, 'app': 3, 'browse': 1, 'store': 1, 'buy': 1, 'stuff': 1, 'talk': 1, 'friends': 2, 'etc': 1, 'get': 2, 'rid': 3, 'ability': 1, 'chat': 1, 'need': 1, 'separate': 1, 'nice': 1, 'mobile': 1, 'authentication': 1, 'widget': 1, 'thank': 1, 'make': 1, 'worse': 1, 'dirty': 1, 'heathens': 1}
{'poorly': 1, 'design': 1, 'ui': 1, 'extremely': 1, 'slow': 1, 'laggy': 1, 'load': 3, 'library': 1, 'old': 2, 'app': 4, 'work': 1, 'fine': 1, 'take': 1, 'break': 1, 'fix': 1, 'result': 1, 'bad': 1, 'might': 1, 'expect': 1, 'give': 1, 'us': 1, 'back': 1, 'edit': 1, 'currently': 1, 'black': 1, 'friday': 1, 'autumn': 1, 'sale': 1, 's': 1, 'store': 1, 'page': 1, 'keep': 1, 'say': 1, 'problem': 1, 'web': 1, 'content': 1, 'solution': 1, 'find': 1, 'literally': 1, 'make': 1, 'less': 1, 'likely': 1, 'spend': 1, 'money': 1, 'steam': 1, 'simply': 1, 'unable': 1}
{'boot': 1, 'pc': 1, 'today': 1, 'steam': 3, 'app': 3, 'ask': 2, 'user': 2, 'id': 2, 'password': 2, 'something': 1, 'enter': 1, 'years': 1, 'obviously': 1, 'remember': 1, 'click': 1, 'help': 1, 'sign': 1, 'link': 1, 'tell': 1, 'open': 2, 'phone': 2, 'scan': 1, 'qr': 1, 'code': 1, 'literally': 1, 'way': 1, 'get': 1, 'around': 1}
{'literally': 1, 'sign': 1, 'account': 1, 'mobile': 1, 'anymore': 1, 'keep': 3, 'ask': 1, 'authenticate': 1, 'steamguard': 1, 'code': 1, 'go': 1, 'type': 1, 'letter': 1, 'jumble': 1, 'around': 1, 'keyboard': 1, 'dissapearing': 1, 'find': 2, 'anywhere': 1, 'contact': 1, 'steam': 2, 'support': 1, 'email': 1, 'list': 1, 'site': 1, 'send': 1, 'response': 1, 'back': 1, 'say': 1, 'longer': 1, 'monitor': 1, 'none': 1, 'self': 1, 'help': 1, 'question': 1, 'fit': 1, 'situation': 1, 'open': 2, 'ticket': 1, 'use': 1, 'love': 1, 'even': 1}
{'terrible': 1, 'sign': 2, 'website': 1, 'instal': 1, 'app': 2, 'get': 2, 'see': 1, 'screen': 1, 'authenticate': 1, 'email': 2, 'twice': 1, 'everything': 1, 'go': 4, 'way': 1, 'past': 1, 'point': 1, 'continue': 1, 'actually': 1, 'create': 1, 'account': 1, 'steam': 1, 'leave': 1, 'two': 1, 'attempt': 1, 'page': 1, 'manually': 1, 'automatic': 1, 'prompt': 1, 'system': 1, 'place': 1, 'try': 1, 'third': 1, 'time': 1, 'pretty': 1, 'sure': 1, 'know': 1}
{'2': 1, 'years': 1, 'ago': 1, 'email': 1, 'verification': 1, 'issue': 2, 'account': 1, 'creation': 1, 'people': 1, 'still': 1, 'talk': 1, 'recently': 1, 'review': 1, 'contact': 1, 'customer': 1, 'support': 1, 'steam': 1, 'impossible': 2, 'try': 1, 'return': 1, 'game': 2, 'honestly': 1, 'one': 1, 'worst': 1, 'run': 1, 'operations': 1, 'ever': 1, 'experience': 1, 'pc': 1, 'buy': 1, 'download': 1, 'video': 1}
{'garbage': 1, 'site': 1, 'support': 2, 'use': 1, 'years': 1, 'never': 1, 'happy': 1, 'website': 1, 'let': 1, 'log': 3, 'even': 1, 'verify': 1, 'account': 1, 'change': 1, 'password': 1, 'prompt': 1, 'download': 1, 'app': 1, 'steam': 2, 'pc': 1, 'laptop': 1, 'phone': 1, 'get': 2, 'captcha': 1, 'anti': 1, 'robot': 1, 'stick': 1, 'infinite': 1, 'loop': 1, 'select': 1, 'pics': 1, 'bicycle': 1, 'buss': 1, 'way': 1, 'contact': 1, 'without': 1, 'already': 1}
{'much': 1, 'improve': 1, 'ui': 2, 'nice': 1, 'things': 1, 'seem': 1, 'optimize': 1, 'less': 1, 'stutter': 1, 'overall': 1, 'always': 1, 'room': 1, 'improvement': 1, 'think': 1, 'run': 1, 'well': 1, '4': 1, '5': 2, 'edit': 1, '10': 1, '13': 1, '22': 1, 'steam': 1, 'recently': 1, 'change': 1, 'terrible': 1, 'focus': 1, 'completely': 1, 'store': 1, 'click': 1, 'least': 1, '2': 1, 'icons': 1, 'get': 1, 'friends': 1, 'top': 1, 'plain': 1, 'slow': 1, 'use': 1, 'app': 1, '2fa': 1, 'uninstalled': 1, '1': 1}
{'currently': 1, 'unusable': 1, 'steam': 2, 'guard': 2, 'authentication': 2, 'annoy': 3, 'hold': 1, 'breath': 1, 'update': 2, 'nobody': 1, 'valve': 1, 'read': 1, 'anymore': 1, 'use': 1, 'simple': 1, 'lightweight': 1, 'useful': 1, 'work': 2, 'fine': 1, 'bite': 1, 'often': 2, 'code': 1, 'change': 1, 'lead': 1, 'wait': 1, 'jump': 1, 'play': 1, 'limit': 1, 'schedule': 1, 'allow': 1, 'qr': 1, 'cod': 1, 'probably': 2, 'someone': 2, 'raise': 1, 'else': 1, 'suggest': 1, 'mobile': 1, 'app': 1, 'match': 1, 'new': 2, 'pc': 1, 'client': 1}
{'buy': 3, 'romance': 1, 'three': 1, 'kingdoms': 1, 'game': 4, 'steam': 4, 'gameplay': 1, 'technical': 1, 'issue': 1, 'resolve': 1, 'request': 1, 'refund': 1, 'refuse': 1, 'provide': 1, 'one': 1, 'two': 1, 'weeks': 1, 'since': 1, 'initially': 1, 'direct': 1, 'publisher': 1, 'support': 1, 'hear': 1, 'back': 1, 'number': 1, 'years': 1, 'say': 1, 'trust': 1}
{'genuinely': 1, 'worst': 1, 'sign': 2, 'in': 1, 'create': 1, 'account': 3, 'process': 1, 'ever': 2, 'see': 1, 'app': 1, 'sometimes': 1, 'captcha': 1, 'work': 1, 'reverify': 1, 'get': 1, 'send': 1, 'email': 1, 'verify': 2, 'click': 1, 'take': 1, 'page': 1, 'actually': 1, 'complicate': 1}
{'quite': 1, 'literally': 1, 'impossible': 2, 'create': 2, 'account': 3, 'need': 1, 'input': 1, 'email': 3, 'confirm': 2, 'take': 1, 'sign': 2, 'screen': 1, 'try': 1, 'online': 1, 'also': 1, 'matter': 1, 'captha': 1, 'always': 1, 'fail': 1, 'incredible': 1, 'waste': 1, 'time': 1}
{'app': 1, 'slow': 1, 'load': 1, 'scroll': 1, 'overly': 1, 'sensitive': 1, 'link': 1, 'game': 1, 'break': 1, 'sometimes': 1, 'direct': 1, 'right': 1, 'spot': 1, 'time': 2, 'take': 2, 'store': 2, 'home': 1, 'page': 1, 'front': 1, 'interest': 1, 'place': 1, 'keep': 1, 'explore': 1, 'long': 1, 'enough': 1, 'spend': 1, 'good': 1, 'amount': 1, 'hunt': 1, 'hide': 1, 'gems': 1, 'become': 1, 'wall': 1, 'garden': 1, 'experience': 1}
{'want': 1, 'sell': 1, 'steam': 2, 'items': 2, 'without': 1, 'wait': 1, '15': 1, 'days': 1, 'verify': 1, 'listings': 1, 'stop': 1, 'need': 2, 'mobile': 1, 'authenticator': 1, 'get': 2, 'app': 1, 'try': 1, 'set': 3, 'go': 1, 'whole': 1, 'process': 1, 'tell': 1, 'repeatedly': 1, 'one': 1, 'thing': 1, 'like': 1, 'way': 1, 'hold': 1}
{'qr': 1, 'code': 1, 'update': 1, 'steam': 4, 'guard': 2, 'someone': 1, 'easily': 1, 'able': 1, 'hack': 1, 'account': 2, 'block': 1, 'steal': 1, 'personal': 1, 'information': 1, 'credit': 1, 'card': 1, 'thousands': 1, 'dallors': 1, 'worth': 1, 'game': 2, 'items': 1, 's': 1, '2': 1, 'step': 1, 'mobile': 1, 'varification': 1, 'never': 1, 'alert': 1, 'anyone': 1, 'else': 1, 'log': 1, 'try': 1, 'communicate': 1, 'w': 1, 'support': 1, 'help': 1, 'almost': 1, 'none': 1, 'existent': 1, 'extremely': 1, 'slow': 1, 'non': 1, 'remorseful': 1, 'situation': 1, 'unreliable': 1, 'untrustworthy': 1, 'client': 1, 'uninstalling': 1}
{'experience': 1, 'steam': 1, 'across': 1, 'devices': 1, 'leave': 1, 'much': 1, 'desire': 1, 'never': 1, 'even': 2, 'let': 2, 'sign': 2, 'pete': 1, 's': 1, 'sake': 1, 'loosen': 1, 'recaptcha': 1, 'reach': 1, 'support': 1, 'multiple': 1, 'time': 1, 'response': 1, 'automate': 1, 'get': 2, 'message': 1, 'do': 1, 'suck': 1, 'hear': 1, 'lot': 1, 'good': 1, 'things': 1, 'company': 1, 'word': 1, 'back': 1, 'better': 1}
{'like': 2, 'get': 2, 'second': 1, 'app': 4, 'chat': 1, 'old': 2, 'open': 1, 'friends': 2, 'list': 2, 'right': 1, 'away': 1, 'reason': 1, 'main': 1, 'use': 2, 'steam': 2, 'see': 3, 'online': 1, 'click': 1, 'hope': 1, 'revert': 1, 'back': 1, 'version': 1, 'want': 1, 'delete': 1, 'rely': 1, 'discord': 1, 'play': 1, 'stay': 1, 'way': 1}
{'app': 3, 'horrible': 2, 'work': 4, '75': 1, 'time': 2, 'say': 1, 'error': 1, 'load': 1, 'page': 1, '1gb': 1, 'fiber': 1, 'internet': 1, 'speed': 1, 'connection': 1, 'steam': 3, 'chat': 1, 'better': 1, 'able': 1, 'message': 1, 'friends': 1, 'pc': 1, 'amaze': 1, 'phone': 1, 'need': 1, 'fix': 1, '25': 1}
{'pretty': 1, 'bad': 1, 'actually': 2, 'buy': 2, 'anything': 1, 'paypal': 1, 'app': 2, 'issue': 1, 'year': 1, 'plan': 1, 'fix': 1, 'remove': 1, 'chat': 1, 'functionality': 1, 'another': 1, 'work': 1, 'either': 1, 's': 2, 'use': 1, 'steam': 1, 'guard': 1, 'even': 1, 'bother': 1, 'browse': 1, 'game': 1, 'might': 1, 'well': 1, 'stick': 1, 'mobile': 1, 'web': 1, 'browser': 1}

## 4. Using Scikit Sklearn

In [50]:
def generate_bow_scikit(contents):
    cv = CountVectorizer()
    
    corpus = []
    for sentence in contents:
        corpus.append(sentence)

    independentFeatures = cv.fit_transform(corpus).toarray()
    return independentFeatures

positive_bow_scikit = generate_bow_scikit(positive_df["content"])

print(positive_bow_scikit)

negative_bow_scikit = generate_bow_scikit(negative_df["content"])

print(negative_bow_scikit)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]